Projeto.Presentation/Controllers/LoginController.cs
using Projeto.BLL;
using Projeto.Presentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Projeto.Presentation.Controllers
{
    public class LoginController : Controller
    {
        private UsuarioBusiness usuarioBusiness;
        private LoginViewModel loginViewModel = new LoginViewModel();

        public LoginController()
        {
            usuarioBusiness = new UsuarioBusiness();
        }

        public ActionResult Index()
        {
            bool isBrowserSupported;

            isBrowserSupported = false;

            isBrowserSupported = (((Request.Browser.Browser.Equals("Chrome") &&
                                    Request.Browser.MajorVersion >= 45) ||

                                   (Request.Browser.Browser.Equals("Firefox") &&
                                    Request.Browser.MajorVersion >= 38) ||

                                   (Request.Browser.Browser.Equals("Edge") &&
                                    Request.Browser.MajorVersion >= 12) ||

                                   (Request.Browser.Browser.Equals("IE") || Request.Browser.Browser.Equals("InternetExplorer")) &&
                                    Request.Browser.MajorVersion >= 10) ||

                                   (Request.Browser.Browser.Equals("Opera") &&
                                    Request.Browser.MajorVersion >= 30));

            if (!isBrowserSupported)
            {
                string navegador;

                navegador = string.Format($@" <br/><b>Seu Navegador está desatualizado.</b><br/>
                                              Navegador: { Request.Browser.Browser} <br/>
                                              Versão: { Request.Browser.MajorVersion}");

                Response.Write(navegador);

                return View("IndexErroNavegador");
            }
            else
            {
                return View(loginViewModel);
            }
        }

        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel loginViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var retornoAutenticacao = usuarioBusiness.AutenticarLogin(loginViewModel.Login.ToUpper(), loginViewModel.Senha.Trim());

                    if (retornoAutenticacao.Success)
                    {
                        FormsAuthentication.SetAuthCookie(retornoAutenticacao.Usuario.USU_LOGIN, false);
                        Session["usuarioLogado"] = retornoAutenticacao.Usuario;

                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["Mensagem"] = retornoAutenticacao.Message;
                        return View("Index", loginViewModel);
                    }
                }

                TempData["Mensagem"] = "Campos não preenchidos";
                return View("Index", loginViewModel);
            }
            catch (Exception e)
            {
                TempData["Mensagem"] = "Não foi possível realizar o login";
                return View("Index", loginViewModel);
            }

        }

        public ActionResult Logout()
        {
            Session["usuarioLogado"] = null;

            return RedirectToAction("Index");
        }
    }
}

Projeto.Presentation/Controllers/PlanejamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Projeto.Entities;
using Projeto.BLL;
using Projeto.Presentation.Models;
using AutoMapper;
using System.Text;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.html.simpleparser;
using System.Web;
using Projeto.Presentation.Authorization;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using Excel = Microsoft.Office.Interop.Excel;
using System.Runtime.InteropServices;

namespace Projeto.Presentation.Models
{
    public class PlanejamentoController : Controller
    {
        private readonly PlanejamentoBusiness business;
        private readonly string constClientes;


        public PlanejamentoController()
        {
            business = new PlanejamentoBusiness();
            constClientes = "CLIENTES";
        }

        [Authorization("ADM", "CON")]
        public ActionResult ConsultaPIP()
        {
            List<PlanejamentoConsultaPIPViewModel> lista = new List<PlanejamentoConsultaPIPViewModel>();

            try
            {
                lista = Mapper.Map<List<PlanejamentoConsultaPIPViewModel>>(business.ConsultarPlanejamento());
            }
            catch (Exception e)
            {
                TempData["Mensagem"] = e.Message;
            }

            return View(lista);
        }

        [Authorization("ADM", "CON")]
        public ActionResult ConsultaPainel(string PLA_REGIONAL,
                                           string PLA_PROCESSO,
                                           string TIP_TIPO_PROCESSO,
                                           string estadoDoConjunto,
                                           string PLA_CONJUNTO,
                                           string PLA_STATUS_PROGRAMACAO,
                                           bool localTronco = false,
                                           bool localRamal = false,
                                           bool realizarConsulta = false)
        {
            var PlanejamentoConsulta = new DTO.PlanejamentoConsultaPainelDTOViewModel
            {
                RegionaisList = ObterRegionais(),
                ProcessosList = ObterProcessosPorRegional(PLA_REGIONAL),
                TiposDeProcessosList = ObterTiposDeProcessosPorProcesso(PLA_PROCESSO),
                EstadosDosConjuntosList = ObterEstadosDosConjuntosPorTipoDeProcesso(PLA_REGIONAL, PLA_PROCESSO, TIP_TIPO_PROCESSO),
                ConjuntosList = ObterConjuntosPorEstadoDoConjunto(PLA_REGIONAL, PLA_PROCESSO, TIP_TIPO_PROCESSO, estadoDoConjunto),
                StatusDasProgramacoesList = ObterStatusDasProgramacoesPorConjunto(PLA_REGIONAL, PLA_PROCESSO, TIP_TIPO_PROCESSO),
                PLA_REGIONAL = PLA_REGIONAL,
                PLA_PROCESSO = PLA_PROCESSO,
                TIP_TIPO_PROCESSO = TIP_TIPO_PROCESSO,
                EstadoDoConjunto = estadoDoConjunto,
                PLA_CONJUNTO = PLA_CONJUNTO,
                PLA_STATUS_PROGRAMACAO = PLA_STATUS_PROGRAMACAO,
                LocalTronco = localTronco,
                LocalRamal = localRamal,
                RealizarConsulta = realizarConsulta,
                ConsultaPlanejamentoList = new List<PlanejamentoConsultaPainelViewModel>()
            };

            ViewBag.PLA_REGIONAL = PLA_REGIONAL;
            ViewBag.PLA_PROCESSO = PLA_PROCESSO;
            ViewBag.TIP_TIPO_PROCESSO = TIP_TIPO_PROCESSO;
            ViewBag.EstadosDoConjunto = estadoDoConjunto;
            ViewBag.PLA_CONJUNTO = PLA_CONJUNTO;
            ViewBag.PLA_STATUS_PROGRAMACAO = PLA_STATUS_PROGRAMACAO;
            ViewBag.LocalTronco = localTronco;
            ViewBag.LocalRamal = localRamal;
            ViewBag.RealizarConsulta = realizarConsulta;

            if (realizarConsulta)
            {
                if ((!string.IsNullOrEmpty(PLA_REGIONAL) && !string.IsNullOrEmpty(PLA_PROCESSO) && PLA_PROCESSO == constClientes) ||
                    (!string.IsNullOrEmpty(PLA_REGIONAL) && !string.IsNullOrEmpty(PLA_PROCESSO) && !string.IsNullOrEmpty(TIP_TIPO_PROCESSO)))
                {
                    var lista = Mapper.Map<List<PlanejamentoConsultaPainelViewModel>>(business.ConsultarProducao(PLA_REGIONAL,
                                                                                                                 PLA_PROCESSO,
                                                                                                                 TIP_TIPO_PROCESSO,
                                                                                                                 estadoDoConjunto,
                                                                                                                 PLA_CONJUNTO,
                                                                                                                 PLA_STATUS_PROGRAMACAO,
                                                                                                                 localTronco,
                                                                                                                 localRamal));

                    foreach (var item in lista)
                    {
                        var planejamento = new PlanejamentoConsultaPainelViewModel()
                        {
                            TMP_TIPO_PROCESSO = item.TMP_TIPO_PROCESSO,
                            PLA_RANKING_DEC_ATUAL_REGION = item.PLA_RANKING_DEC_ATUAL_REGION,
                            PLA_RANKING_FEC_ATUAL_REGION = item.PLA_RANKING_FEC_ATUAL_REGION,
                            PLA_RANKING_CLIENTE = item.PLA_RANKING_CLIENTE,
                            PLA_PROJETO = item.PLA_PROJETO,
                            PLA_CONJUNTO = item.PLA_CONJUNTO,
                            PLA_ALIMENTADOR = item.PLA_ALIMENTADOR,
                            PLA_IDENTIFICADOR = item.PLA_IDENTIFICADOR,
                            PLA_DISPOSITIVO = item.PLA_DISPOSITIVO,
                            PLA_ACAO = item.PLA_ACAO,
                            PLA_UNIDADE = item.PLA_UNIDADE,
                            PLA_QUANTIDADE_EXECUTADA = item.PLA_QUANTIDADE_PENDENTE,
                            PLA_QTD_SERVICOS_DISPOSITIVO = item.PLA_QTD_SERVICOS_DISPOSITIVO,
                            PLA_QUANTIDADE_PENDENTE = item.PLA_DISPOSITIVO_PENDENTE_PRO,
                            PLA_GAP_CONH_DEZ_ANEEL = item.PLA_GAP_CONH_DEZ_ANEEL,
                            PLA_GAP_CONI_DEZ_ANEEL = item.PLA_GAP_CONI_DEZ_ANEEL,
                            PLA_VALOR_TOTAL = item.PLA_VALOR_TOTAL
                        };
                        PlanejamentoConsulta.ConsultaPlanejamentoList.Add(planejamento);
                    }

                    ViewBag.LoadGraph = true;
                }
                else
                {
                    TempData["Mensagem"] = @"Campos obrigatórios para realizar a consulta:<br />
                                              - Regional<br />
                                              - Processo<br />
                                              - Indicador (se Processo for diferente de 'CLIENTES')";
                }
            }

            return View(PlanejamentoConsulta);
        }

        [Authorization("ADM", "CON")]
        public ActionResult ConsultaDadosProgramacao(string PLA_DISPOSITIVO,
                                                     string PLA_PROJETO,
                                                     bool consultarProgramacao = false)
        {
            var ProgramacaoConsulta = new DTO.PlanejamentoConsultaPainelDTOViewModel
            {
                PLA_DISPOSITIVO = PLA_DISPOSITIVO,
                ProjetosList = ObterProjetosPorDispositivo(PLA_DISPOSITIVO),
                PLA_PROCESSO = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 1),
                OTCorrecao = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 2),
                PLA_CONJUNTO = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 3),
                PLA_ALIMENTADOR = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 4),
                PLA_TOTAL_CLIENTES = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 5),
                PLA_STATUS_PROGRAMACAO = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 6),
                PLA_QUANTIDADE_PLANO_ATUAL = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 7),
                PLA_QUANTIDADE_PENDENTE = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 8),
                PLA_ACAO = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 9),
                PLA_UNIDADE = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 10),
                PLA_IDENTIFICADOR = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 11),
                PLA_GAP_CONH_DEZ_ANEEL = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 12),
                PLA_GAP_CONI_DEZ_ANEEL = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 13),
                PLA_REGIONAL = ObterCampoPorDispositivoProjeto(PLA_DISPOSITIVO, PLA_PROJETO, 14),
                ConsultarProgramacao = consultarProgramacao,
                ConsultaPlanejamentoList = new List<PlanejamentoConsultaPainelViewModel>(),
                ConsultaProgramacaoList = new List<ProgramacaoConsultaViewModel>()
            };

            ViewBag.PLA_DISPOSITIVO = PLA_DISPOSITIVO;
            ViewBag.PLA_PROJETO = PLA_PROJETO;
            ViewBag.ConsultarProgramacao = consultarProgramacao;

            if (consultarProgramacao)
            {
                if (!string.IsNullOrEmpty(PLA_DISPOSITIVO) && !string.IsNullOrEmpty(PLA_PROJETO) && !string.IsNullOrEmpty(ProgramacaoConsulta.PLA_IDENTIFICADOR))
                {
                    var businessProgramacao = new ProgramacaoBusiness();

Projeto.Presentation/Views/Shared/Layout.cshtml
@using Projeto.Entities
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Projeto PIP</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/Content/css/principal.css" rel="stylesheet" />

</head>
<body>
    <div>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark justify-content-between" style="padding-top: 0px;
    padding-bottom: 0px;">
            <a class="navbar-brand" href="#">
                <img src="~/Images/-logo.png" width="160" height="80" alt="">
            </a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Sistema para Planejamento Integrado da Produção (PIP) <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                @{Usuario usuario = (Usuario)Session["usuarioLogado"]; }
                @if (usuario != null)
                {
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">@usuario.USU_NOME</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="@Url.Action("Logout","Login")">Sair</a>
                            </div>
                        </li>
                    </ul>
                }
            </div>
        </nav>

        <nav class="navbar navbar-expand-sm navbar-dark bg-dark" style="padding-top: 0px;
    padding-bottom: 0px;">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="~/Home/Index">Página inicial</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Planejamento
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @*TODO: remover dps*@
                            @*<a class="dropdown-item" href="~/Planejamento/ConsultaDadosProgramacao?PLA_DISPOSITIVO=MC24269">Teste para histórico</a>*@
                            <a class="dropdown-item" href="@Url.Action("ConsultaPainel", "Planejamento")">Painel de Produção</a>
                            @*TODO: remover dps*@
                            @*<a class="dropdown-item" href="~/Planejamento/ConsultaPIP">Planejamento Integrado da Produção (PIP)</a>*@
                        </div>
                    </li>

                    @*TODO: remover dps*@
                    @*<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Programação
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="~/Programacao/Cadastro?PRO_PLA_IDENTIFICADOR=4222&PLA_REGIONAL=MACA%C3%89&PLA_DISPOSITIVO=MC24269&PRO_DISPOSITIVO=MC24269&PLA_PROJETO=802408_MC24269&PLA_UNIDADE=un&PRO_QUANTIDADE_CLIENTE=140&PRO_IMPACTO_CONH=149.975&PRO_IMPACTO_CONI=16.300">Teste para programar</a>
                <a class="dropdown-item" href="~/Programacao/Cadastro">Cadastro</a>
                <a class="dropdown-item" href="~/Programacao/Consulta">Consulta</a>
            </div>
        </li>*@

                    @*TODO: remover dps*@
                    @*<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Equipe
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="~/Equipe/Cadastro?EQP_PRO_IDENTIFICADOR=11&PLA_REGIONAL=MACA%C3%89">Teste para inserir equipe</a>
                <a class="dropdown-item" href="~/Equipe/Cadastro">Cadastro</a>
                <a class="dropdown-item" href="~/Equipe/Consulta">Consulta</a>
            </div>
        </li>*@

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Funcionalidades
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Exportar", "Planejamento")">Exportar dados para o Excel</a>
                        </div>
                    </li>

                </ul>
            </div>
        </nav>
    </div>


    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <div class="container-fluid">
        @RenderBody()
    </div>

    <div id="janelacarregamento" class="modal" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered modal-sm">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="spinner-border" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <br />
                    <br />
                    Processando, por favor aguarde.
                </div>
            </div>
        </div>
    </div>

</body>
</html>